#server:
#  applicationConnectors:
#    -type:http
#     port:8080
#  adminConnectors:
#    -type:http
#     port:8081
#
#logging:
#  level:INFO

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

database:
  url: jdbc:postgresql://localhost:5432/training
  user: postgres
  password: postgres